openapi: 3.0.0
info:
  title: Hotel Booking Service – initiate_booking
  version: 1.0.3
  description: >
    Create a new booking and update room availability by supplying all booking details
    as query parameters.

paths:
  /initiate_new_bookings:
    get:
      summary: initiate_booking – create booking record and update inventory
      description: >
        Takes the following as query parameters: `check_in_date`, `check_out_date`,
        `number_of_guests`, `guest_name`, `email`, `phone`, and `room_id`.  
        Calculates `paid_amount` = `price_per_day` × nights, writes a new item into
        `booking_details`, and updates `available_from` = `check_out_date` in
        `room_inventory`.
      operationId: initiate_new_bookings
      parameters:
        - name: check_in_date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Booking check‑in date (YYYY‑MM‑DD)
        - name: check_out_date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Booking check‑out date (YYYY‑MM‑DD)
        - name: number_of_guests
          in: query
          required: true
          schema:
            type: integer
          description: Number of guests for the booking
        - name: guest_name
          in: query
          required: true
          schema:
            type: string
          description: Full name of the guest
        - name: email
          in: query
          required: true
          schema:
            type: string
            format: email
          description: Guest’s email address
        - name: phone
          in: query
          required: true
          schema:
            type: string
          description: Guest’s phone number (digits only)
        - name: room_id
          in: query
          required: true
          schema:
            type: string
          description: Identifier of the room to book
      responses:
        "200":
          description: Booking created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  booking_id:
                    type: string
                    description: Generated unique booking identifier
                  paid_amount:
                    type: number
                    description: Total charged amount (price_per_day × nights)
                  status:
                    type: string
                    description: Booking status (e.g., "CONFIRMED")
        "400":
          description: Missing or invalid input parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Missing one or more required parameters"
        "422":
          description: Validation errors such as invalid date range or missing room pricing
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Room R103 not found or missing price_per_day"
        "500":
          description: Internal server error during booking operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unexpected error: <details>"